language: generic
sudo: required
dist: trusty

env:
  global:
    - secure: cHLp/ejbr+fhBwjiGqEmtHpR1gMbMmCx3s9Hgn4tJzC9eJFtgql6Ign+dtoEFBNzQtml/pdA0AK870EIh18rfaiuiePKkVuXklUicY0iud1AzZNgW+t1oyOaKT65uJ7DBWVEzeHc09yviMg7Gg+qo3wxTkYP6P0x8ZpGWA2ctwCxYGGjw8CVmLj3X7FKCrCIU7QtVoRW7QnxSN7ZG4sFQeuadS7JaGPNosVOlTEggGVnJ3zG62XZvHiZKw2yFmbavYmaKmQMxRzmzIe9jm8BfHRneBkviZ9CBMMwgGhG0J0yo2XBS9wY0FHVdopz3wHWBpmmjEPAgw/RY+gk6ddIyBxNywWyNF14cVAoCZnQLo+8mk4kzjyJnqbQ0+ai14gOMLr1DvqcwdF3m+yhlkLmCk0qn2FWAMyKMT3J5N7JxjYRZdRVAxo/zCYVqhoEsSdb/w4xVKAIAJHv1pbVCuxXIZ0fcHlBv5dnxXtvWaUjsiXovmlg5L+UODL6695DTnAOpxDHBN8O3Yf6Q4ML65xyhHge1LWe2M1Kt+vIz/ygojUsUm4WQcXYSa+ehwZfiSm1/JewjcYvdXPNz6a+X+j079aeivJ8TOHJ1Gg6np050+5bsad5+eIti+Jw4E0mhHGtfVTdVJhF1qk91698pNRrgLhsEx0pf9JD1eTi+vHClr8=
    - secure: SXLMGSRp12omM+VZawITYPQdQqrvTv37kcDZMJ84znfM23GlRe0XoszsDvgd7w1wJgDSxzf+MDU6aryse1JijWIIPqrRp98vqU0MXZyDVA3qQZ/a8epF3aTB7oqzDaezMim+PEVAahMH6TnjpEbWYltitAHpMB3iQ/YvGvi7NStxFdx5P4PM/TrIkan+NBMAp47LqkDcehM0Ok8LkGwcqrPU6KxnvdALBuWCtA9jQQMA+FY8ZsMeCimvmZhnFeOkqzHHkGgGUkCDUw3jh52tkXE9J9kOFFNyI4ZkLJ2ilw/vrOxTMvwN2LTSmh1D8PI1us6n6DW9qZP1+FYGEMc5N4YgjOxhwWJDvpVmi0LIsSquZoCyiH/xp6kMCKu9SQz0fxrh/73UMTkQYNQwpzti/BWfqdkGEe2Eo+uL1HiGKjOpUlCrR9KMKhX2BPzdK4yKjEIprC4EVYiWPUvu1S67uwhX+qLNP9GF/R7+ue8wM2RxyKPgXqny74YKZ0LFlhYvE0u8wy9B9vHOY4dhKfjNgVdxSidnI24sQl1AliDEq9i/7cAwwGK6qXpSPWH0mIRRZkxDnfNzN9uXfdCL38RAEs1K0fmGLA2LvRlzvoR8/7Himytv0KSTnZ5C0aSYKjaHlksv37Ud24V2CK+zVa9IyZ+7ocB8rlG/DChgV3BbMZk=
    - secure: FYz04RvkY5p3Jl7kISsVfmDS4GvzXbSoFer3j8XsnR03N+aFJWBtKtYKtSD9Dg0tF+fpRB4gkUqC2dcVaYdQIXpSClCD/2PxLudaSaKgkJilJXiqzr2E1XUjrmuyPfPLajPs76g/f0SAHFnTuO1/wVBHU+FCz6BQIPsZTxQxbO3spo2SzEKM8plJSyq7AYlVDUjsQk0cZb92yp0QliEAtW/OHoysHZEiirWTNrgpFYDIOTwuGF9TT1HV5YWlGZNsgFgRpru4t0GQja9wsOUOjPhEDFr14qhUBRRnyqINhP63+54iK7kMOO9WNsaCSPNR0JU/Ts+hLooFAbeYmwSX/Ryr+6w1PzAHZpohKfz7PC++qLJMAj5J3IkRu/sqEPepqU8sf6nV0kSsyhcZwiygF0nHMicThz+dxuIHjP4ZmYOJGiqh06+4BWu3qkCVlI9totKE26aZqUDDauN0mxIbmkJGb3cvF4JDKEi+p4l9hVNXF3JGqzku3DvXgJU2Vh4u/sswBgXaqE9HMzPMohBtJB1pnh1VyVlPjWuBYLo08kZltu95fQAc+6NudTleZz7ywrnEyc0MpM80C2PPTkrZAiifU+9XY1OkZU5emdMAngwF4IlJYavFpxSmu6vJjH2B3XdL+Dsly1DkGabSkMN4FF7l9FBBnFZGDuQAuwP+UcE=

matrix:
  include:
    - env: ZSH=zsh-4.3.5
    - env: ZSH=zsh-4.3.6
    - env: ZSH=zsh-4.3.7
    - env: ZSH=zsh-4.3.8
    - env: ZSH=zsh-4.3.9
    - env: ZSH=zsh-4.3.10
    - env: ZSH=zsh-4.3.11
    - env: ZSH=zsh-4.3.12
    - env: ZSH=zsh-4.3.13
    - env: ZSH=zsh-4.3.14
    - env: ZSH=zsh-4.3.15
    - env: ZSH=zsh-4.3.16
    - env: ZSH=zsh-4.3.17
    - env: ZSH=zsh-5.0.0
    - env: ZSH=zsh-5.0.1
    - env: ZSH=zsh-5.0.2
    - env: ZSH=zsh-5.0.3
    - env: ZSH=zsh-5.0.4
    - env: ZSH=zsh-5.0.5
    - env: ZSH=zsh-5.0.6
    - env: ZSH=zsh-5.0.7
    - env: ZSH=zsh-5.0.8
    - env: ZSH=zsh-5.1
    - env: ZSH=zsh-5.1.1
    - env: ZSH=zsh-5.2
    - env: ZSH=zsh-5.3
    - env: ZSH=zsh-5.3.1
    - env: ZSH=master


before_script:
  - DOCKER_HUB_REPO=zshusers/zsh-${ZSH#zsh-}

script:
  - docker build -t $DOCKER_HUB_REPO --build-arg url=https://api.github.com/repos/zsh-users/zsh/tarball/${ZSH} .

after_success:
  - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  - docker tag $DOCKER_HUB_REPO:${TRAVIS_COMMIT::8} $DOCKER_HUB_REPO:latest
  - docker push $DOCKER_HUB_REPO
