language: generic
sudo: required
dist: trusty

env:
  - ZSH=4.3.11
  - ZSH=4.3.17
  - ZSH=5.0.0
  - ZSH=5.1.1
  - ZSH=5.2
  - ZSH=5.3
  - ZSH=5.3.1
  - ZSH=master

before_script:
  - uname -a
  - docker --version
  - REPOSITORY=zshusers/zsh-$ZSH_VERSION

script:
  - docker build -t $REPOSITORY --build-arg url=https://api.github.com/repos/zsh-users/zsh/tarball/${ZSH} .

after_success:
  - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  - docker tag $REPOSITORY:${TRAVIS_COMMIT::8} $REPOSITORY:latest
  - docker push $REPOSITORY
