language: generic
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  global:
  - secure: fBtsagZDw01CGdtZNwgrGKRU6Cvbg6YQTynQK9oO60XI1ZARrMk2hOfsqMqKPSLDOi8mzabZa0W7xwPs3SgnEp6qBnkJsTrzzBPETgxdZW8PxApRfgmvWNsCBnOesTYctTB/IA6Aq5WDszhQ8roRuc0xlrvAFAflv1TMeD+yOa96OtWbwQetiieo7U0A1p3u2Q9JekcT0Ya2B9LoaVSVs8wv0Z4nnv7JU1oSvgn9VXMSih/kbLueXljGFOiPsZiUiHDhWUcAT/iTwXwf80nVbQiUwHHp/G4902Yg9xavlo4SB6+fUA76hfStr+ddl3bPZ1jQPy9YpEs6oDvS4+9qfnWA4HU1V0IRD5NuVhnwd9dfVxIaXdf4jtdlkK+XBY25DTCDgnaUo0QGhyuykkFsM4bTICzpcBeuZUFlib6CHxveeaaMoWAvVkSEa3p0nC+PEnL5h7LnfN6k++kuO2f5O9H1jwuyKo6/DAdsrhomhgzd7yUSt4EyUdVxAw9eri6pBGgiQF8hiupq3oa2S/JdLONO2uVSBcOO0Acy3e1h7N2uUKZ5eswXRc+aCuJ7PMb2YGsRIB4jafiQRUwYy3Ua/5/vKUhFtWblS/xqCTuXQVwYrDtSDWOLep/S/uZ7eypwo9PqnROXAIsM9qOdUa+oZigD4Y9+amyTWuXjLVOffEA=
  - secure: fBELJ3ecsZ0Fd2x1mX/6sYLIxj4QwlqvF/enKJTJHae8iuPLgxhfA/8VjWhX8llvsSxXURZjGdT5buz2gHrOp7auzji8o2GgFXccSCKmhbPm9X3QFuxTa3YPh3qn6RYdkW1OD9PhOM/wQfCWJZX4JtmAhqoE3cvyw/WLmukVw90Vei9Q5RuE8EVHqNNjwzOe52mrEyiIZrq3iDW0woUyhkJ9h9+DNuS2GfMMt5wFELIc3mUEh5ica9YIdBashTZrbHS++bzuG94ajxlHmXtqGrgE/Pd4knQNdJ7NUg5O5U5zsumVaLKb8i9DjQSo+1v/aQylY0QhSVL0mYU/Yh+id/VFzwkbG/72pJGn0glqtZjZ7p7PV9N8lJNbYUgw8EXLN9XLuAFaDnNfKz5/pZVaj+XtazmAmbnlksBq0BNvoGr2i/BG6Do/CNR4wQv46pLkCIXMuaoEoyF0xXp2bv2G0ibZkwP6aN8xuUV6XpZ6mvkd4nKOCgups18PCwNeeVc8tqpsTGDtgdSHAk8eEEDh1OCnd7RHlbtRBKNz0f1+Jl2YN/mtMBxAwWHtJU31ckuMl/Vc5Jjl4xpcz7OKo4+lGXChffHlNSP3UbevcN1lE0QM8LKwF+TuJ0dqxdjQo9tdresFxQgkQL0GwMMF6KHM0hNqolfLOzE8WUr88ANtZKs=

matrix:
  include:
    - env: VERSION=master
    - env: VERSION=zsh-5.7.1
    - env: VERSION=zsh-5.7
    - env: VERSION=zsh-5.6.2
    - env: VERSION=zsh-5.6.1
    - env: VERSION=zsh-5.6
    - env: VERSION=zsh-5.5.1
    - env: VERSION=zsh-5.5
    - env: VERSION=zsh-5.4.2
    - env: VERSION=5.4.1
    - env: VERSION=5.4
    - env: VERSION=zsh-5.3.1
    - env: VERSION=zsh-5.3
    - env: VERSION=zsh-5.2
    - env: VERSION=zsh-5.1.1
    - env: VERSION=zsh-5.1
    - env: VERSION=zsh-5.0.8
    - env: VERSION=zsh-5.0.7
    - env: VERSION=zsh-5.0.6
    - env: VERSION=zsh-5.0.5
    - env: VERSION=zsh-5.0.4
    - env: VERSION=zsh-5.0.3
    - env: VERSION=zsh-5.0.2
    - env: VERSION=zsh-5.0.1
    - env: VERSION=zsh-5.0.0
    - env: VERSION=zsh-4.3.17
    - env: VERSION=zsh-4.3.16
    - env: VERSION=zsh-4.3.15
    - env: VERSION=zsh-4.3.14
    - env: VERSION=zsh-4.3.13
    - env: VERSION=zsh-4.3.12
    - env: VERSION=zsh-4.3.11

script:
  - make build

deploy:
  provider: script
  script: make deploy
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8a6d841b50ce6343e8a5
    on_success: change
    on_failure: always
    on_start: never
  irc:
    channels:
      - "chat.freenode.net#zsh-docker"
    on_success: change
    on_failure: always
    on_start: never
    use_notice: true
