language: generic
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  global:
    - secure: "BhlRX2t0DKdbHrtFJ8oAk9iu/ukWcGF0ryV6fETWDAxusqZyjIVimsxQRuB0hrGqWhXG20UhwUXWO/XoUIWN67ShKfXkQ/cyZTwHMVlvtkbpV2P5nfQFHHel0g8H+7kthyHM8qL2tnaMLkNDaCv/X94Bi7FlRXVIjntUYHl1SNEz3Ki7Sr3GqReCiKiJb7mt1ZhNSGgVYz40NIYhNNnRKbw2Ryro1vockZc+7b7D6g/ENkgiuWpL/nUXtal5Yd4bQcUz2w8PIa/DMD8XQkpE+exroZHeqfL+MO3ZRBftCD5jCYvBtQZhmBH7TeAehBib3/Z1KZMWITOGnBeDg39SWLk1JGz0r86RaUQBN0CB7MgF/ZabemRYuuP0jWyKVgJRJ4miobtuS2M/hpinuoi/eTrrC+noBlRgfdewhE+/CRA6Dn/qQbTrvqo1EZAR3xy93W7U6ACX4/p0g/EfO2h/07oH/S0uRKFPmIqI0YVCr9oY4vY5s1xWKC7RWEQYn+kN3OERfhTLRNcr3wUwlS7UOrKo26Wj/kIjev+KZu/md6zGO+1a3wlRN3SrY+UPLDEpXrIyXKMYlkm3OXCsxZ+02l+/Rf+HjHIPBVn6pEhkTSfXmar3XXTQerbDdXkK9uydOZ/gh0YrGtqDSO1j2cJRZw+SsUtSmaTjFYtbcRYbUn8="
    - secure: "hKy9QK7H8l/fNe70JiAyV8EQKmwKrrY7AU0CHFI5znshrmCpoHyAX+tHFz5HY3qBIxLEPdHlkvAn7Cp12bE51NkXCxAD5kKKrHBLAdJiXsQJZEZS6yuOPGFXYds8hkhR3frwS2h3S5dpahETYPsayJsOTxhWN4DQtzD+I/47LJMDqYpjlFdSpHXWl9xudnT7EylKE31iACZ7tMOP2LPHOLaeUzjBv1iJADGsnyb4ue1gwHJucnlHURonn4W94tFuyNpPgaQmbvff7hcBVRcazPo36o8TNXWX1p0aSAjrGtAFhm3k0brwCysMtZAZ82x9Xv+PTSaD2lsbTgOl4yEZjrDoQ8um4AsixT85GKV3tDht0nqzU1RkK9hiodbgtU107aMrTUkl0X+F2ev4y1FfQQ4Ow03Z52gHgT8Kj8sqEx7c0mi8jdwm2pLs51iCictJugDMnfejxRM95/RgdSuOxvB0x9SercHVApNMoyu9dCcjvwgvsEb4WwRXrPnNFtFXejRaiwHSIzLtLs59Al30IpMV6cn425HbqxDg/pVCcOjjP1yzwKjYuwtvrjmxpts3qedM+Sze4it1dfs/ATlmsoz/7CPiBLmhJKwmoj6JHFU6xZZ9IoEoxStZP3U2yB6hBEnzOfvLL2IXu+SwtbdmCEvC0Dia+k4H0UpGzgCwNYw="
matrix:
  include:
    - env: VERSION=master
    - env: VERSION=zsh-5.7.1
    - env: VERSION=zsh-5.7
    - env: VERSION=zsh-5.6.2
    - env: VERSION=zsh-5.6.1
    - env: VERSION=zsh-5.6
    - env: VERSION=zsh-5.5.1
    - env: VERSION=zsh-5.5
    - env: VERSION=zsh-5.4.2
    - env: VERSION=5.4.1
    - env: VERSION=5.4
    - env: VERSION=zsh-5.3.1
    - env: VERSION=zsh-5.3
    - env: VERSION=zsh-5.2
    - env: VERSION=zsh-5.1.1
    - env: VERSION=zsh-5.1
    - env: VERSION=zsh-5.0.8
    - env: VERSION=zsh-5.0.7
    - env: VERSION=zsh-5.0.6
    - env: VERSION=zsh-5.0.5
    - env: VERSION=zsh-5.0.4
    - env: VERSION=zsh-5.0.3
    - env: VERSION=zsh-5.0.2
    - env: VERSION=zsh-5.0.1
    - env: VERSION=zsh-5.0.0
    - env: VERSION=zsh-4.3.17
    - env: VERSION=zsh-4.3.16
    - env: VERSION=zsh-4.3.15
    - env: VERSION=zsh-4.3.14
    - env: VERSION=zsh-4.3.13
    - env: VERSION=zsh-4.3.12
    - env: VERSION=zsh-4.3.11

script:
  - make build

deploy:
  provider: script
  script: make deploy
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: change
    on_start: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8a6d841b50ce6343e8a5
    on_success: change
    on_failure: always
    on_start: never
  irc:
    channels:
      - "chat.freenode.net#zsh-docker"
    on_success: change
    on_failure: always
    on_start: never
    use_notice: true
